### ISSUE TITLE
Guildcard Parsing Returning Erroneous GC Numbers

### ISSUE THREAD

**Issue by PhantomPhire** [phelix-/psostats-client#7]
When parsing for guild card numbers, sometimes non-zero whitespace characters (such as "\u0001", "\u0002", "\u0004") are returned. It would seem the guild card string offset is in a slightly different position between clients; when testing on Ephinea, the guild card number starts 4 bytes after the provided offset, and if any of the 4 preceding bytes are not 0x00, it will be parsed as part of, or all of the guild card number.

**Comment by phelix-** [comment]
Thanks for looking into this. I just verified that unseen GCs start at the beginning of the offset so we can't (universally) just push it back a few bytes.

My first reaction is just trim until we hit number characters and we can refine from there if that turns out to not work 100% of the time, but I'm onboard for whatever you want to try.

**Comment by phelix-** [comment]
Should be fixed by #14
